version: '1'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
       - ./:/app
